### ISSUE TITLE
ImportError: cannot import name 'Group'

### ISSUE THREAD

**Issue by dawntcherian** [unhangout/django-channels-presence#10]
I am using channels==2.0.2 and getting the following error while trying to import Group.

File "/home/user/python_projects/django_channels/my_project/game/models.py", line 3, in <module>
` from channels import Group`
ImportError: cannot import name 'Group'

**Comment by luk156** [comment]
there is a plan to update the library to channels2?

**Comment by luk156** [comment]
could you merge changes from https://github.com/ivahotin/django-channels-presence?

**Comment by luk156** [comment]
ping

**Comment by boiyelove** [comment]
Please merge the changes so that the module can be useable. also please update the module on pypi

**Comment by pwnchaurasia** [comment]
any update on this.. I am trying to use this and it is giving me errors

**Comment by cr4zyd3v** [comment]
So sad.. this is a small but very useful lib.. looks like the dev is not active

**Comment by aliasav** [comment]
hey guys, any update on this!?

**Comment by cr4zyd3v** [comment]
> hey guys, any update on this!?

Hey, you can use this fork: https://github.com/ivahotin/django-channels-presence
user @ivahotin just updated it to channels v2 but looks like this repo is not being maintained anymore.. So you can use the fork without any problems

**Comment by aliasav** [comment]
> > hey guys, any update on this!?
> 
> Hey, you can use this fork: https://github.com/ivahotin/django-channels-presence
> user @ivahotin just updated it to channels v2 but looks like this repo is not being maintained anymore.. So you can use the fork without any problems

thanks a lot, I'll use this fork!

**Comment by yourcelf** [comment]
It's been a long time, but I've now merged support for Django Channels 2.4 along with docs updates.
