### ISSUE TITLE
support for django2.0

### ISSUE THREAD

**Issue by iliya-hajjar** [unhangout/django-channels-presence#17]
there is an error like :
user=user if (user and user.is_authenticated()) else None
`TypeError: 'bool' object is not callable`
'TypeError: 'bool' object is not callable'
Of course the problem could be solved by changing the following line :
`user=user if (user and user.is_authenticated()) else None`
to:
`user=user if (user and user.is_authenticated) else None`
but I wanted to know if there is a way like new version or new package to solve this problem. I'm using this package `django-channels-presence==0.0.7`

**Comment by yourcelf** [comment]
The version of Django you are using (something greater than 2.0, which removed support for `is_authenticated()` as a method) is not supported by django-channels-presence v0.0.7.

The latest version of django-channels-presence is v1.0.0; however this version targets django-channels v2.4, which is backwards-incompatible with django-channels v1.

If you are using Django > 2.0, but django-channels < 2.0, you will need to fork django-channels-presence to add compatibility for the newer Django but older channels.
