### ISSUE TITLE
Import channels module name conflict

### ISSUE THREAD

**Issue by akermen** [unhangout/django-channels-presence#3]
The import line: `from channels import Group` in "channels_presence/models.py" conflicts with [django-channels](https://channels.readthedocs.io/en/stable/installation.html) module:
`File ".../channels_presence/models.py", line 12, in <module>
    from channels import Group
ImportError: cannot import name Group`

It appears to be referring local "channels.py" file instead of global channels module.

Python version: 2.7.11
Django version: 1.10.3

**Comment by yourcelf** [comment]
I just pushed a [commit](https://github.com/unhangout/django-channels-presence/commit/92662dd7b78ea007c194a82794314c0163d6c68e) that should fix this, by turning on "absolute imports" within that file.  Could you please try the latest master and see if that fixes it?  If so, I'll push a new release to pypi.

I'm primarily using python 3, so hadn't needed to enable it explicitly.

**Comment by akermen** [comment]
yes, with a minor typo fix:
`from __future__ import unicode_literals, absolute_import`
(without **s** character at the end).

**Comment by yourcelf** [comment]
Oops, thanks. :)

**Comment by yourcelf** [comment]
Release 0.0.6 published with that fix.
